// ===== Salle =====
function parseRx(rx){const m=String(rx||'').match(/(\d+)\s*[×xX]\s*(\d+)(?:\s*-\s*(\d+))?/);return m?{n:+m[1],lo:+m[2],hi:+(m[3]||m[2])}:{n:3,lo:10,hi:10}}
// Double progression : toutes les séries au haut de la fourchette -> on monte la charge ; sinon +1 rep
function nextTarget(exId,rx){const r=parseRx(rx),lp=lastPerf(exId),x=EXM[exId]||{};if(!lp)return null;const n=Math.max(r.n,1);const sets=lp.sets;const kg=lp.max;const step=kgStep(exId);
const top=sets.filter(s=>(+s.kg||0)>=kg);const allTop=sets.length>=n&&top.every(s=>s.reps>=r.hi)&&top.length>=Math.min(n,sets.length);
if(exId==='gainage'){const best=Math.max(...sets.map(s=>s.reps));return{kg:0,reps:Array(n).fill(best+5),up:false,msg:`Objectif du jour : ${best+5} secondes par série.`}}
if(x.eq==='corps'&&kg===0){if(allTop)return{kg:0,reps:Array(n).fill(r.hi),up:true,msg:`Tu as fait ${n} × ${r.hi} : ajoute du lest (ceinture ou haltère) ou passe à une variante plus dure.`};return{kg:0,reps:Array.from({length:n},(_,k)=>Math.min(r.hi,((sets[k]||sets[sets.length-1]).reps||r.lo)+1)),up:false,msg:'Objectif du jour : une rep de plus par série.'}}
if(allTop){const nk=Math.round((kg+step)*10)/10;return{kg:nk,reps:Array(n).fill(r.lo),up:true,msg:`Tu as validé ${n} × ${r.hi} à ${fmtKg(kg)} kg : on monte à ${fmtKg(nk)} kg, objectif ${r.lo} reps.`}}
return{kg,reps:Array.from({length:n},(_,k)=>{const s=sets[k]||sets[sets.length-1];const base=(+s.kg||0)>=kg?s.reps:r.lo-1;return Math.max(r.lo,Math.min(r.hi,(base||r.lo)+1))}),up:false,msg:`Objectif du jour : ${fmtKg(kg)} kg, une rep de plus que la dernière fois. Quand tu tiens ${r.hi} reps partout, la charge monte.`}}
function ensureRows(e){if(e.rows)return;const r=parseRx(e.rx),t=nextTarget(e.exId,e.rx);e.rows=[];const n=Math.min(Math.max(r.n,1),10);for(let k=0;k<n;k++){e.rows.push(t?{reps:t.reps[k],kg:t.kg||'',done:false}:{reps:r.hi,kg:'',done:false})}e.tgt=t?{msg:t.msg,up:t.up}:null}
function syncSets(e){e.sets=e.rows.filter(r=>r.done).map(r=>({reps:r.reps,kg:+r.kg||0}))}
const kgStep=id=>(EXM[id]||{}).eq==='halteres'?1:2.5;
// Minuteur de repos : démarre quand une série est validée. On garde l'heure de fin, donc il reste juste même si l'écran se verrouille.
let actx=null;
function audioUnlock(){try{actx=actx||new(window.AudioContext||window.webkitAudioContext)();if(actx.state==='suspended')actx.resume()}catch(e){}}
function beep(){if(!actx)return;try{[0,.25,.5].forEach(d=>{const o=actx.createOscillator(),g=actx.createGain(),t=actx.currentTime+d;o.frequency.value=880;o.connect(g);g.connect(actx.destination);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.3,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.18);o.start(t);o.stop(t+.2)})}catch(e){}}
function restFor(e){const P=S.profile;return e.exId!=='gainage'&&parseRx(e.rx).lo<=8?(+P.restHeavy||0):(+P.rest||0)}
function startRest(act,sec){if(sec>0)act.rest={end:Date.now()+sec*1000,total:sec};else delete act.rest}
function drawRest(){const a=activeSession(),r=a&&a.rest,box=$('#rest');const show=!!r&&tab==='gym';box.hidden=!show;document.body.classList.toggle('resting',show);if(!r)return;
const left=Math.ceil((r.end-Date.now())/1000);
if(left<=0){if(!r.rung){r.rung=true;if(left>-5){beep();if(navigator.vibrate)navigator.vibrate([200,100,200])}save()}
if(left<-10){delete a.rest;save();box.hidden=true;document.body.classList.remove('resting');return}}
box.classList.toggle('over',left<=0);$('#restLab').textContent=left<=0?'Repos terminé':'Repos';$('#restT').textContent=left<=0?'Go !':Math.floor(left/60)+':'+pad(left%60);$('#restBar').style.width=(left<=0?0:Math.min(100,left/r.total*100))+'%';$('#restGo').textContent=left<=0?'OK':'Passer'}
ACT.restadj=el=>{const a=activeSession(),r=a&&a.rest;if(!r)return;const now=Date.now();r.end=Math.max(now,Math.max(r.end,now)+(+el.dataset.d)*1000);r.rung=false;r.total=Math.max(r.total,Math.ceil((r.end-now)/1000));save();drawRest()};
ACT.restskip=()=>{const a=activeSession();if(a)delete a.rest;save();drawRest()};
function rowsHTML(e,i){ensureRows(e);const sec=e.exId==='gainage';return `<div class="srows"><div class="shead"><span>N°</span><span>${sec?'Secondes':'Reps'}</span><span>Charge (kg)</span><span></span></div>${e.rows.map((r,k)=>`<div class="srow ${r.done?'ok':''}"><span class="snum">${k+1}</span>
<div class="step"><button class="sb" data-act="sstep" data-i="${i}" data-k="${k}" data-f="reps" data-d="-1" aria-label="Moins de répétitions">−</button><input class="sin" data-i="${i}" data-k="${k}" data-f="reps" inputmode="numeric" value="${r.reps}" aria-label="Répétitions série ${k+1}"><button class="sb" data-act="sstep" data-i="${i}" data-k="${k}" data-f="reps" data-d="1" aria-label="Plus de répétitions">+</button></div>
<div class="step"><button class="sb" data-act="sstep" data-i="${i}" data-k="${k}" data-f="kg" data-d="-1" aria-label="Moins de charge">−</button><input class="sin" data-i="${i}" data-k="${k}" data-f="kg" inputmode="decimal" value="${r.kg===''?'':String(r.kg).replace('.',',')}" placeholder="0" aria-label="Charge série ${k+1}"><button class="sb" data-act="sstep" data-i="${i}" data-k="${k}" data-f="kg" data-d="1" aria-label="Plus de charge">+</button></div>
<button class="sok" data-act="sdone" data-i="${i}" data-k="${k}" aria-label="${r.done?'Série validée, toucher pour annuler':'Valider la série '+(k+1)}" aria-pressed="${r.done}">${ic('check',18)}</button></div>`).join('')}
<div class="srowact"><button class="link" data-act="saddrow" data-i="${i}">+ Ajouter une série</button>${e.rows.length>1&&!e.rows[e.rows.length-1].done?`<button class="link" style="color:var(--mute)" data-act="sdelrow" data-i="${i}">Retirer la dernière</button>`:''}</div></div>`}
function rowOf(el){const act=activeSession();if(!act)return null;const e=act.exercises[+el.dataset.i];if(!e||!e.rows)return null;return{act,e,r:e.rows[+el.dataset.k],k:+el.dataset.k}}
ACT.sstep=el=>{const o=rowOf(el);if(!o||!o.r)return;const f=el.dataset.f,d=+el.dataset.d;if(f==='reps')o.r.reps=Math.max(0,(parseInt(o.r.reps,10)||0)+d);else o.r.kg=Math.max(0,Math.round(((+o.r.kg||0)+d*kgStep(o.e.exId))*10)/10);if(o.r.done){o.r.done=false;syncSets(o.e)}save();render()};
ACT.sdone=el=>{const o=rowOf(el);if(!o||!o.r)return;if(!o.r.done&&!(parseInt(o.r.reps,10)>0)){toast('Indique le nombre de répétitions');return}o.r.done=!o.r.done;o.r.reps=parseInt(o.r.reps,10)||0;o.r.kg=o.r.kg===''?0:+o.r.kg;if(o.r.done){for(const nx of o.e.rows.slice(o.k+1))if(!nx.done&&(nx.kg===''||nx.kg===0))nx.kg=o.r.kg;o.act.last=Date.now();audioUnlock();startRest(o.act,restFor(o.e))}else delete o.act.rest;syncSets(o.e);save();render()};
ACT.saddrow=el=>{const act=activeSession();if(!act)return;const e=act.exercises[+el.dataset.i];if(!e)return;ensureRows(e);const last=e.rows[e.rows.length-1]||{reps:10,kg:''};e.rows.push({reps:last.reps,kg:last.kg,done:false});save();render()};
ACT.sdelrow=el=>{const act=activeSession();if(!act)return;const e=act.exercises[+el.dataset.i];if(!e||!e.rows||e.rows.length<2)return;if(e.rows[e.rows.length-1].done)return;e.rows.pop();save();render()};
document.addEventListener('input',ev=>{const t=ev.target;if(!t.classList||!t.classList.contains('sin'))return;const o=rowOf(t);if(!o||!o.r)return;if(t.dataset.f==='reps')o.r.reps=parseInt(t.value,10)||0;else o.r.kg=t.value.trim()===''?'':num(t.value);const row=t.closest('.srow');if(o.r.done){o.r.done=false;syncSets(o.e);if(row)row.classList.remove('ok')}save()});
document.addEventListener('focusin',ev=>{if(ev.target.classList&&ev.target.classList.contains('sin'))ev.target.select()});
function exCard(e,i){const x=EXM[e.exId];if(!x)return '';const lp=lastPerf(e.exId);const curMax=e.sets.length?Math.max(...e.sets.map(s=>+s.kg||0)):null;let delta='';
if(lp&&curMax!=null){const bw=lp.max===0&&curMax===0,u=bw?' '+exUnit(e.exId):' kg';const d=bw?Math.max(...e.sets.map(s=>+s.reps||0))-lp.best:Math.round((curMax-lp.max)*10)/10;delta=d>0?`<p class="up">${ic('up',13)} +${fmtKg(d)}${u} depuis la dernière fois</p>`:d<0?`<p class="mute">${fmtKg(d)}${u} par rapport à la dernière fois</p>`:''}
return `<div class="card ex"><div style="display:flex;align-items:center;gap:6px"><button class="exhead grow" data-act="exinfo" data-ex="${e.exId}"><span class="pict">${exPic(x)}</span><span class="grow"><strong>${x.n}</strong><small>${e.rx?'Objectif '+e.rx+(lp?', ':''):''}${lp?`dernière fois ${fmtPerf(e.exId,lp)}`:(e.rx?'':'Première fois : vas-y tranquille')}</small></span></button><button class="iconbtn sm" data-act="exedit" data-i="${i}" aria-label="Modifier ${x.n}">${ic('dots',20)}</button></div>
${(()=>{ensureRows(e);return e.tgt?`<p class="tgt ${e.tgt.up?'up2':''}">${e.tgt.up?ic('up',14):ic('bolt',14)} ${e.tgt.msg}</p>`:''})()}${rowsHTML(e,i)}${delta}</div>`}
function tipHTML(act){let msg='';for(const e of act.exercises){if(stagnating(e.exId)){const x=EXM[e.exId];const v=(x.v||[]).map(id=>EXM[id]).find(Boolean);const h=exHistory(e.exId);msg=`Tu bloques à ${fmtPerf(e.exId,h[h.length-1])} (${x.n}) depuis 3 séances.${v?` Essaie ${v.n.toLowerCase()} pour relancer la progression.`:' Tente une répétition de plus par série.'}`;break}}
if(!msg){const nx=act.exercises.find(e=>!e.sets.length);if(nx&&!act.exercises.some(e=>e.sets.length)){const lp=lastPerf(nx.exId);msg=`Commence par ${EXM[nx.exId].n.toLowerCase()}${nx.rx?', '+nx.rx:''}. Fais d’abord une série légère pour t’échauffer.`+(lp?` La dernière fois tu étais à ${fmtPerf(nx.exId,lp)}.`:'')}else if(nx){msg=`Prochain exercice : ${EXM[nx.exId].n.toLowerCase()}${nx.rx?', '+nx.rx:''}.`}}
if(!msg&&act.exercises.length){const missing=act.groups.find(g=>!act.exercises.some(e=>exG(e.exId)===g));if(missing){const s=EX.find(x=>x.g===missing);msg=`Rien encore pour les ${GN[missing].toLowerCase()} : ${s.n.toLowerCase()} serait un bon choix.`}}
if(!msg&&!act.exercises.length){const g=act.groups[0];const picks=EX.filter(x=>x.g===g).slice(0,2).map(x=>x.n.toLowerCase());msg=`Pour commencer : ${picks.join(', puis ')}.`}
return msg?`<div class="coach"><div class="avatar">${ic('bolt',16)}</div><div class="bubble"><p>${msg}</p></div></div>`:''}
function tilesHTML(){return `<div class="tiles">${GROUPS.map(([g,n])=>{const d=daysSince(g);const cls=d==null?'':d<=1?'ok':d<=3?'mid':'late';return `<div class="tile ${cls}"><small>${n}</small><strong>${d==null?'—':d===0?'auj.':d+' j'}</strong></div>`}).join('')}</div>`}
function fmtChrono(ms){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor(s/60)%60,x=s%60;return (h?h+':'+pad(m):pad(m))+':'+pad(x)}
function planCard(p,isToday){const ex=(p.exercises||[]).filter(e=>EXM[e.exId]);return `<div class="card prog ${isToday?'rec':''}"><div class="sh" style="margin-top:0"><h2>${p.style?STYLES[p.style].n+' : ':''}${groupsLabel(p.groups)}</h2><span class="${isToday?'badge':'lab0'}">${isToday?p.time:fmtDay(p.date)+', '+p.time}</span></div>${ex.length?`<ul class="plist">${ex.map(e=>`<li><button class="plink" data-act="exinfo" data-ex="${e.exId}">${EXM[e.exId].n}</button><span class="rx">${esc(e.rx)}</span></li>`).join('')}</ul>`:'<p class="empty">Aucun exercice choisi.</p>'}
<div class="actions" style="margin:12px 0 0"><button class="btn ghost" data-act="editplan" data-id="${p.id}">Modifier</button><button class="btn ${isToday?'primary':'ghost'} grow2" data-act="startplan" data-id="${p.id}">${isToday?'Commencer':'Commencer maintenant'}</button></div>${framed?'':`<button class="link" style="display:flex;align-items:center;gap:6px;margin-top:6px" data-act="ics" data-id="${p.id}">${ic('calendar',16)} Ajouter à l’agenda</button>`}</div>`}
function renderGym(){const act=activeSession();let body='';
if(act){const doneN=act.exercises.filter(e=>e.sets.length).length;
body=staleHTML(act)+`<div class="chrono"><p class="lab0">${act.style?STYLES[act.style].n+' : ':''}${groupsLabel(act.groups)}</p><p class="clock" id="chrono">${fmtChrono(Date.now()-act.start)}</p><p class="lab0">${doneN} / ${act.exercises.length} exercices commencés</p></div>`
+act.exercises.map((e,i)=>exCard(e,i)).join('')+tipHTML(act)+`<p class="note">Touche ⋯ sur un exercice pour le remplacer, le déplacer, changer l’objectif ou le retirer.</p><div class="actions"><button class="btn ghost" data-act="addex">${ic('plus')} Exercice</button><button class="btn primary" data-act="finish">Terminer la séance</button></div>`}
else{const ps=S.plans.filter(p=>p.date>=dk()).sort((a,c)=>(a.date+a.time)<(c.date+c.time)?-1:1);const todays=ps.filter(p=>p.date===dk()),next=ps.find(p=>p.date!==dk());
body=missedHTML()+(todays.length?`<p class="lab0" style="margin-bottom:8px">Séance du jour</p>`+todays.map(p=>planCard(p,true)).join(''):`<div class="card" style="text-align:center;padding:22px 16px"><p style="font-weight:600;font-size:17px">Aucune séance prévue aujourd’hui</p><p class="note">Tu vas quand même à la salle ? Prépare ta séance en quelques secondes.</p><button class="btn primary full" data-act="plannow">${ic('calendar')} Planifier ma séance</button></div>`+(next?`<p class="lab">Ou avance ta prochaine séance</p>`+planCard(next,false):''))}
$('#v-gym').innerHTML=`<header class="top"><h1>Salle</h1></header>${body}`}
ACT.startplan=el=>{const p=S.plans.find(x=>x.id===el.dataset.id);if(!p)return;if(activeSession()){toast('Une séance est déjà en cours');return}S.plans=S.plans.filter(x=>x.id!==p.id);S.sessions.push({id:uid(),date:dk(),start:Date.now(),groups:p.groups.slice(),style:p.style||null,exercises:(p.exercises||[]).filter(e=>EXM[e.exId]).map(e=>({exId:e.exId,rx:e.rx,sets:[]})),done:false});save();render();window.scrollTo(0,0);toast('C’est parti, chrono lancé')};
ACT.addex=()=>{const act=activeSession();if(!act)return;const order=[...act.groups,...GROUPS.map(g=>g[0]).filter(g=>!act.groups.includes(g))];
sheet(`<h2>Ajouter un exercice</h2><button class="link" data-act="newex" data-ctx="sess">+ Créer un exercice</button>`+order.map(g=>`<p class="lab">${GN[g]}</p>`+EX.filter(x=>x.g===g).map(x=>`<button class="row" data-act="pickex" data-ex="${x.id}"><span class="pict sm">${exPic(x,24)}</span><span class="grow"><strong>${x.n}</strong><small>${x.m}</small></span>${act.exercises.some(e=>e.exId===x.id)?'<span class="acc">ajouté</span>':''}</button>`).join('')).join(''))};
ACT.pickex=el=>{const act=activeSession();if(act&&!act.exercises.some(e=>e.exId===el.dataset.ex)){act.exercises.push({exId:el.dataset.ex,rx:rxFor(el.dataset.ex,false),sets:[]});saveCustom(act)}save();closeSheet();render()};
ACT.exinfo=el=>{const x=EXM[el.dataset.ex];if(!x)return;const lp=lastPerf(x.id);const act=activeSession();const inSess=act&&act.exercises.some(e=>e.exId===x.id);
sheet(`<h2>${x.n}</h2>${exPhoto(x)}<p><strong>${x.m}</strong></p><ul class="cues">${x.c.map(c=>`<li>${c}</li>`).join('')}</ul>${lp?`<p class="note">Record : ${fmtRecord(x.id,exRecord(x.id))}</p>`:''}${x.v.length?`<p class="lab">Variantes</p>`+x.v.map(id=>EXM[id]).filter(Boolean).map(v=>`<div class="row"><button class="exhead grow" data-act="exinfo" data-ex="${v.id}"><span class="pict sm">${exPic(v,24)}</span><span class="grow"><strong>${v.n}</strong><small>${v.m}</small></span></button>${inSess&&!act.exercises.some(e=>e.exId===v.id)?`<button class="link" data-act="swapex" data-from="${x.id}" data-to="${v.id}">Remplacer</button>`:ic('chev',18)}</div>`).join(''):''}${act&&!inSess?`<button class="btn primary full" data-act="pickex" data-ex="${x.id}">Ajouter à la séance</button>`:''}${x.u&&!x.off?`<div class="grid2"><button class="btn ghost full" data-act="editmyex" data-ex="${x.id}">Modifier</button><button class="btn ghost full warn" data-act="delmyex" data-ex="${x.id}">Supprimer</button></div>`:''}`)};
// Exercices personnalisés. ctx : 'sess' (ajout direct à la séance en cours), 'plan' (ajout à la séance en préparation) ou '' (réglages)
function exForm(x,ctx){const act=activeSession();const g0=x?x.g:ctx==='plan'&&PD?(PD.pick>=0?EXM[PD.exercises[PD.pick].exId].g:PD.groups[0]):ctx==='sess'&&act?act.groups[0]:'pecs';const eq0=x?x.eq:'machine';
sheet(`<h2>${x?'Modifier l’exercice':'Créer un exercice'}</h2><form id="exF" class="form" novalidate><label>Nom<input name="n" autocomplete="off" maxlength="40" value="${esc(x?x.n:'')}" placeholder="Tirage à l’élastique"></label>
<div class="grid2"><label>Muscle<select name="g">${GROUPS.map(([g,n])=>`<option value="${g}" ${g===g0?'selected':''}>${n}</option>`).join('')}</select></label><label>Matériel<select name="eq">${Object.entries(EQN).map(([k,n])=>`<option value="${k}" ${k===eq0?'selected':''}>${n}</option>`).join('')}</select></label></div>
<label>Où, quelle machine (facultatif)<input name="m" autocomplete="off" maxlength="80" value="${esc(x?x.m||'':'')}" placeholder="Machine au fond à gauche"></label>
<label>Consignes, une par ligne (facultatif)<textarea name="c" rows="3" style="min-height:90px">${esc(x&&Array.isArray(x.c)?x.c.join('\n'):'')}</textarea></label>
<button class="btn primary full" type="submit">${x?'Enregistrer':'Créer l’exercice'}</button></form>`);
const f=$('#exF'),F=f.elements;f.addEventListener('submit',ev=>{ev.preventDefault();const n=cleanTx(F.n.value).slice(0,40);if(n.length<2){toast('Donne un nom à l’exercice');return}
if(EX.some(e=>e.id!==(x&&x.id)&&e.n.toLowerCase()===n.toLowerCase())){toast('Un exercice porte déjà ce nom');return}
const rec={id:x?x.id:'u'+uid(),n,g:F.g.value,eq:F.eq.value,m:cleanTx(F.m.value).slice(0,80),c:F.c.value.split('\n').map(cleanTx).filter(Boolean).slice(0,6)};
S.myEx=Array.isArray(S.myEx)?S.myEx:[];const k=S.myEx.findIndex(e=>e.id===rec.id);if(k>=0)S.myEx[k]=rec;else S.myEx.push(rec);syncEx();
const a2=activeSession();if(!x&&ctx==='sess'&&a2){a2.exercises.push({exId:rec.id,rx:rxFor(rec.id,false),sets:[]});saveCustom(a2)}else if(!x&&ctx==='plan'&&PD&&PD.pick!=null)pdPickApply(PD.pick,rec.id);
save();closeSheet();render();toast(x?'Exercice modifié':'Exercice créé')})}
ACT.newex=el=>exForm(null,el.dataset.ctx||'');
ACT.editmyex=el=>{const x=(S.myEx||[]).find(e=>e.id===el.dataset.ex);if(x)exForm(x,'')};
ACT.delmyex=el=>{const id=el.dataset.ex,x=(S.myEx||[]).find(e=>e.id===id);if(!x)return;const act=activeSession();if(act&&act.exercises.some(e=>e.exId===id)){toast('Retire-le d’abord de la séance en cours');return}
x.off=true;S.plans.forEach(p=>{p.exercises=(p.exercises||[]).filter(e=>e.exId!==id)});for(const k in S.custom||{})S.custom[k]=S.custom[k].filter(e=>e.exId!==id);if(PD)PD.exercises=PD.exercises.filter(e=>e.exId!==id);
syncEx();save();closeSheet();render();toast('Exercice supprimé, ton historique est gardé')};
ACT.swapex=el=>{const act=activeSession();if(!act)return;const e=act.exercises.find(x=>x.exId===el.dataset.from);if(!e)return;if(e.sets.length){toast('Tu as déjà fait des séries sur cet exercice');return}e.exId=el.dataset.to;saveCustom(act);save();closeSheet();render();toast('Exercice remplacé')};
ACT.exedit=el=>{const act=activeSession();if(!act)return;const i=+el.dataset.i,e=act.exercises[i];if(!e)return;const x=EXM[e.exId];
sheet(`<h2>${x.n}</h2><form id="rxF" class="form" novalidate><label>Objectif (séries × répétitions)<input name="rx" autocomplete="off" value="${esc(e.rx||rxFor(e.exId,false))}" placeholder="3 × 10"></label><button class="btn primary full" type="submit">Enregistrer l’objectif</button></form>
<button class="btn ghost full" data-act="replaceex" data-i="${i}">Remplacer par un autre exercice</button>
<div class="grid2"><button class="btn ghost full" data-act="moveex" data-i="${i}" data-d="-1" ${i===0?'disabled':''}>Monter</button><button class="btn ghost full" data-act="moveex" data-i="${i}" data-d="1" ${i===act.exercises.length-1?'disabled':''}>Descendre</button></div>
<button class="btn ghost full warn" data-act="removeex" data-i="${i}">Retirer de la séance${e.sets.length?' (tes séries seront effacées)':''}</button>
${act.style?'<p class="note">Tes changements sont gardés pour la prochaine '+STYLES[act.style].n.toLowerCase()+' '+groupsLabel(act.groups)+'.</p>':''}`);
const f=$('#rxF');f.addEventListener('submit',ev=>{ev.preventDefault();const v=f.elements.rx.value.trim();if(v)e.rx=v;saveCustom(act);save();closeSheet();render();toast('Objectif modifié')})};
ACT.moveex=el=>{const act=activeSession();if(!act)return;const i=+el.dataset.i,j=i+(+el.dataset.d);if(j<0||j>=act.exercises.length)return;const a=act.exercises;[a[i],a[j]]=[a[j],a[i]];saveCustom(act);save();closeSheet();render()};
ACT.removeex=el=>{const act=activeSession();if(!act)return;act.exercises.splice(+el.dataset.i,1);saveCustom(act);save();closeSheet();render();toast('Exercice retiré')};
ACT.replaceex=el=>{const act=activeSession();if(!act)return;const i=+el.dataset.i,e=act.exercises[i];if(!e)return;if(e.sets.length){toast('Séries déjà faites : ajoute plutôt un nouvel exercice');return}const x=EXM[e.exId];
const used=new Set(act.exercises.map(a=>a.exId));const row=v=>`<button class="row" data-act="doreplace" data-i="${i}" data-to="${v.id}"><span class="pict sm">${exPic(v,24)}</span><span class="grow"><strong>${v.n}</strong><small>${v.m}</small></span></button>`;
const vars=x.v.map(id=>EXM[id]).filter(v=>v&&!used.has(v.id));const same=EX.filter(v=>v.g===x.g&&v.id!==x.id&&!used.has(v.id)&&!x.v.includes(v.id));const others=EX.filter(v=>v.g!==x.g&&!used.has(v.id));
sheet(`<h2>Remplacer ${x.n.toLowerCase()}</h2>${vars.length?'<p class="lab">Variantes conseillées</p>'+vars.map(row).join(''):''}${same.length?'<p class="lab">Autres exercices '+GN[x.g].toLowerCase()+'</p>'+same.map(row).join(''):''}`+GROUPS.filter(([g])=>g!==x.g).map(([g,n])=>{const l=others.filter(v=>v.g===g);return l.length?`<p class="lab">${n}</p>`+l.map(row).join(''):''}).join(''))};
ACT.doreplace=el=>{const act=activeSession();if(!act)return;const e=act.exercises[+el.dataset.i];if(!e)return;const was=e.exId;e.exId=el.dataset.to;if(!e.rx||EXM[was].g!==EXM[e.exId].g)e.rx=rxFor(e.exId,false);saveCustom(act);save();closeSheet();render();toast('Exercice remplacé')};
ACT.finish=()=>{const act=activeSession();if(!act)return;const idle=Date.now()-lastAct(act)>45*6e4;if(!endSession(act,idle?lastAct(act):Date.now())){save();render();toast('Séance vide supprimée');return}
save();render();toast(`Séance terminée en ${fmtChrono(act.dur)} : ${fmtN(r0(vol(act)))} kg soulevés`)};
ACT.sess=el=>{const s=S.sessions.find(x=>x.id===el.dataset.id);if(!s)return;sheet(`<h2>${groupsLabel(s.groups)}</h2><p class="note">${fmtDayLong(s.date)}, ${s.dur?fmtChrono(s.dur)+', ':''}${fmtN(r0(vol(s)))} kg soulevés</p>`+s.exercises.map(e=>`<div class="row"><div class="grow"><strong>${(EXM[e.exId]||{}).n||e.exId}</strong><small>${e.sets.map(x=>x.reps+' × '+fmtKg(x.kg)).join(', ')}</small></div></div>`).join('')+`<button class="btn ghost full" data-act="delsess" data-id="${s.id}">Supprimer cette séance</button>`)};
ACT.delsess=el=>{S.sessions=S.sessions.filter(s=>s.id!==el.dataset.id);save();closeSheet();render();toast('Séance supprimée')};

// Séance oubliée : sans série validée depuis 1h30 on propose de la clore, après 6 h on la clôt d'office. La durée s'arrête à la dernière série.
const STALE=90*6e4,STALE_MAX=6*36e5;
const lastAct=a=>a.last||a.start;
const isStale=a=>Date.now()-lastAct(a)>STALE;
function endSession(act,end){act.exercises=act.exercises.filter(e=>e.sets.length);delete act.rest;if(!act.exercises.length){S.sessions=S.sessions.filter(s=>s!==act);return false}act.done=true;act.end=end;act.dur=Math.max(0,end-act.start);return true}
function autoClose(){const a=activeSession();if(!a||Date.now()-lastAct(a)<=STALE_MAX)return;const ok=endSession(a,lastAct(a));save();setTimeout(()=>toast(ok?'Séance oubliée : terminée automatiquement':'Séance vide supprimée'),0)}
function staleHTML(act){if(!isStale(act))return '';return `<div class="card prog miss"><h2>Séance restée ouverte</h2><p class="note">${act.last?'Ta dernière série date d’il y a ':'Séance lancée il y a '}${fmtH((Date.now()-lastAct(act))/36e5)}. Si tu as fini, la durée s’arrêtera à ta dernière série.</p><div class="actions" style="margin:10px 0 0"><button class="btn ghost" data-act="contsess">Je continue</button><button class="btn primary" data-act="finish">Terminer</button></div></div>`}
ACT.contsess=()=>{const a=activeSession();if(!a)return;a.last=Date.now();save();render()};
// Séances prévues mais pas faites : on propose de les reporter
function missedHTML(){return missedPlans().map(p=>`<div class="card prog miss"><div class="sh" style="margin-top:0"><h2>Séance ratée : ${groupsLabel(p.groups)}</h2><span class="lab0">${fmtDay(p.date)}</span></div><p class="note" style="margin-top:0">Elle était prévue mais n’a pas été faite. Reporte-la ou laisse-la tomber.</p><div class="actions" style="margin:10px 0 0"><button class="btn ghost" data-act="delplan" data-id="${p.id}">Laisser tomber</button><button class="btn primary" data-act="replan" data-id="${p.id}">Reporter</button></div></div>`).join('')}
ACT.replan=el=>{const p=S.plans.find(x=>x.id===el.dataset.id);if(!p)return;const busy=d=>S.sessions.some(s=>s.date===d)||S.plans.some(x=>x.id!==p.id&&x.date===d);openPlanEditor(p,busy(dk())?addDays(dk(),1):dk())};

// ===== Volume par semaine =====
function weekVolume(){const ws=weekStart(),we=addDays(ws,6);const v={};GROUPS.forEach(([g])=>v[g]={done:0,plan:0});
for(const s of S.sessions){if(s.date<ws||s.date>we)continue;for(const e of s.exercises){const g=exG(e.exId);if(!g)continue;v[g].done+=s.done?e.sets.length:(e.rows?e.rows.filter(r=>r.done).length:e.sets.length)}}
for(const p of S.plans){if(p.date<dk()||p.date>we)continue;for(const e of p.exercises||[]){const g=exG(e.exId);if(g)v[g].plan+=parseRx(e.rx).n}}return v}
function volumeHTML(){const v=weekVolume(),MAX=20;const rows=GROUPS.map(([g,n])=>{const d=v[g].done,p=v[g].plan,t=d+p;const cls=t>=10?'okv':t>=6?'midv':'lowv';return `<div class="vrow"><span>${n}</span><div class="vbar"><i class="vd" style="width:${Math.min(100,d/MAX*100)}%"></i><i class="vp" style="width:${Math.min(100-Math.min(100,d/MAX*100),p/MAX*100)}%"></i><b style="left:50%"></b></div><span class="${cls}">${d}${p?' +'+p:''}</span></div>`}).join('');
const late=GROUPS.filter(([g])=>g!=='abdos'&&v[g].done+v[g].plan<10).map(([g,n])=>`${n.toLowerCase()} (${v[g].done+v[g].plan})`);
return `<div class="card"><div class="sh" style="margin-top:0"><span class="lab0">Séries par muscle cette semaine</span><span class="lab0">repère : 10 à 20</span></div>${rows}<p class="note">${late.length?'À rattraper : '+late.join(', ')+'. Ajoute des séries dans tes prochaines séances.':'Tous tes muscles sont dans la zone utile. Parfait.'}</p><p class="note" style="font-size:12px">Plein : séries faites. Clair : séries prévues. Trait : 10 séries.</p></div>`}
// ===== Planifier =====
function renderPlanTab(){if(PD){$('#v-plan').innerHTML=PD.pick!=null?planPickHTML():planEditorHTML();if(PD.pick==null)bindPlanEditor();return}const ws=weekStart(),we=addDays(ws,6),goal=S.profile.weekGoal||4;
const done=S.sessions.filter(s=>s.done&&s.date>=ws&&s.date<=we).length;const planned=S.plans.filter(p=>p.date>=dk()&&p.date<=we).length;
const ps=S.plans.filter(p=>p.date>=dk()).sort((a,c)=>(a.date+a.time)<(c.date+c.time)?-1:1);
const dots=Array.from({length:Math.max(goal,done+planned)},(_,k)=>`<span class="dot ${k<done?'d':k<done+planned?'p':''}"></span>`).join('');
const left=Math.max(0,goal-done-planned);
const days=Array.from({length:7},(_,k)=>{const d=addDays(ws,k);const s=S.sessions.find(x=>x.done&&x.date===d);const p=S.plans.find(x=>x.date===d);return `<div class="wd ${d===dk()?'today':''} ${s?'d':p?'p':''}"><small>${JOURS[parseDk(d).getDay()].replace('.','')}</small><strong>${parseDk(d).getDate()}</strong><span>${s?groupsLabel(s.groups).split(' + ')[0]:p?groupsLabel(p.groups).split(' + ')[0]:''}</span></div>`}).join('');
const dn=PDdone&&S.plans.find(p=>p.id===PDdone);
$('#v-plan').innerHTML=`<header class="top"><h1>Planifier</h1></header>${missedHTML()}${dn?`<div class="card prog rec"><div class="sh" style="margin-top:0"><h2>Séance planifiée</h2><button class="iconbtn sm" data-act="pddone" aria-label="Fermer">${ic('x',16)}</button></div><p class="note" style="margin-top:0">${dn.style?STYLES[dn.style].n+' : ':''}${groupsLabel(dn.groups)}, ${fmtDay(dn.date)} à ${dn.time}.</p>${calHTML(dn)}${framed?'<p class="note">Depuis claude.ai, l’app ne peut pas écrire directement dans l’agenda de l’iPhone : elle passe par Google Agenda.</p>':''}</div>`:''}
<div class="card"><div class="sh" style="margin-top:0"><span class="lab0">Cette semaine</span><span class="acc" style="font-weight:600">${done} / ${goal} séances faites</span></div><div class="dots">${dots}</div><div class="week">${days}</div>
<p class="note">${done>=goal?'Objectif de la semaine atteint. Une 5e séance si tu te sens frais, sinon récupère.':left?`Encore ${left} séance${left>1?'s':''} à planifier pour tenir tes ${goal} séances.`:'Ta semaine est planifiée, plus qu’à exécuter.'}</p></div>
<button class="btn primary full" data-act="plan" style="margin:4px 0 16px">${ic('plus')} Planifier une séance</button>
<p class="lab">Dernier entraînement par muscle</p>${tilesHTML()}
<h2 style="margin:18px 0 8px">Séances prévues</h2>${ps.length?ps.map(p=>planCard(p,p.date===dk())).join(''):'<p class="empty">Rien de prévu. Planifie tes prochaines séances pour ne pas improviser à la salle.</p>'}`}
// ===== Progrès =====
let progEx=null;
// o.xs : position de chaque point en jours, pour espacer la courbe selon les vraies dates ; o.f : format des repères max et min
function lineChart(pts,col,o={}){if(pts.length<2)return `<p class="empty">Il faut au moins deux mesures pour tracer la courbe.</p>`;const W=300,h=64,f=o.f||(v=>v),xs=o.xs||pts.map((_,i)=>i),x0=xs[0],xr=(xs[xs.length-1]-x0)||1,min=Math.min(...pts),max=Math.max(...pts),span=max-min||1;const xy=pts.map((v,i)=>[((xs[i]-x0)/xr)*(W-8)+4,h-6-((v-min)/span)*(h-12)]);return `<div class="chartw"><svg class="chart" viewBox="0 0 ${W} ${h}" preserveAspectRatio="none" aria-hidden="true"><polyline points="${xy.map(p=>p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ')}" fill="none" stroke="${col}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round" vector-effect="non-scaling-stroke"/></svg><div class="cscale"><span>${f(max)}</span><span>${max>min?f(min):''}</span></div></div>`}
const dayXs=a=>a.map(x=>diffDays(a[0].date,x.date));
function sleepInsight(){const good=[],bad=[];for(const s of S.sessions.filter(x=>x.done)){const n=S.sleep.find(x=>x.date===s.date);if(!n)continue;(n.hours>=7.5?good:bad).push(vol(s))}
if(good.length>=2&&bad.length>=2){const a=avgA(good),b=avgA(bad);if(!b)return '';const pct=Math.round((a/b-1)*100);return pct>=5?`Après une nuit de 7h30 ou plus, tu soulèves ${pct} % de volume en plus.`:pct<=-5?`Pour l’instant, tes séances après une nuit courte sont plus fortes (${-pct} %).`:'Pour l’instant, ton sommeil change peu tes séances.'}
return 'Note tes nuits quelques semaines pour voir leur effet sur tes séances.'}
function renderProg(){const W=S.weights.slice().sort((a,b)=>a.date<b.date?-1:1);const cur=W.length?W[W.length-1].kg:S.profile.kg;const first=W[0];const dW=first&&W.length>1?cur-first.kg:null;
const withH=EX.filter(x=>exHistory(x.id).length);if(!progEx||!withH.some(x=>x.id===progEx))progEx=withH[0]?withH[0].id:null;const hist=progEx?exHistory(progEx):[],rp=allBW(hist);
const recs=withH.map(x=>Object.assign({x},exRecord(x.id))).filter(r=>r.best>0).sort((a,b)=>a.rp-b.rp||b.best-a.best).slice(0,6);
const sl=S.sleep.slice().sort((a,b)=>a.date<b.date?-1:1).slice(-14);const avg=sl.length?avgA(sl.map(s=>s.hours)):null;
$('#v-prog').innerHTML=`<header class="top"><h1>Progrès</h1></header>
<div class="card"><div class="sh" style="margin-top:0"><span class="lab0">Poids du corps</span>${dW!=null?`<span class="${dW>=0?'pr':'mute'}">${dW>=0?'+':''}${fmtKg(dW)} kg depuis le ${fmtDay(first.date)}</span>`:''}</div><p class="big">${fmtKg(cur)} kg</p>${W.length?lineChart(W.map(w=>w.kg),'var(--prot)',{xs:dayXs(W),f:fmtKg})+(W.length>1?`<div class="axis"><span>${fmtDay(W[0].date)}</span><span>${fmtDay(W[W.length-1].date)}</span></div>`:''):'<p class="empty">Pèse-toi le matin à jeun, une fois par semaine.</p>'}${(()=>{const a=weightAdvice();return a?`<div class="coach" style="margin:10px 0 0"><div class="avatar">${ic('bolt',15)}</div><div class="bubble"><p>${a.msg}</p>${a.delta?`<button class="link" data-act="kcaladj" data-d="${a.delta}">Passer à ${fmtN(S.profile.kcal+a.delta)} kcal</button>`:''}</div></div>`:(W.length?'<p class="note">Pèse-toi 2 à 3 fois par semaine, le matin à jeun : après 2 semaines, le coach ajuste tes calories.</p>':'')})()}<button class="link" data-act="weigh">+ Nouvelle pesée</button></div>
<div class="card">${withH.length?`<div class="sh" style="margin-top:0"><select id="exSel" aria-label="Choisir l’exercice">${withH.map(x=>`<option value="${x.id}" ${x.id===progEx?'selected':''}>${x.n}</option>`).join('')}</select></div><p class="big acc">${fmtPerf(progEx,hist[hist.length-1],rp)}</p>${lineChart(hist.map(h=>rp?h.best:h.max),'var(--acc)',{xs:dayXs(hist),f:rp?(v=>v):fmtKg})}${hist.length>1?`<div class="axis"><span>${fmtDay(hist[0].date)}</span><span>${fmtDay(hist[hist.length-1].date)}</span></div>`:''}`:'<p class="lab0">Charges soulevées</p><p class="empty">Termine une séance pour voir la courbe de tes charges.</p>'}</div>
${recs.length?`<p class="lab">Records</p><div class="recs">${recs.map(r=>`<div class="rec"><span class="acc">${ic('trophy',16)}</span><strong>${fmtRecord(r.x.id,r)}</strong><small>${r.x.n}</small></div>`).join('')}</div>`:''}
${(()=>{const hist=S.sessions.filter(s=>s.done).sort((a,c)=>(c.end||0)-(a.end||0)).slice(0,8);return hist.length?`<h2 style="margin:20px 0 4px">Dernières séances</h2>`+hist.map(s=>`<button class="row" data-act="sess" data-id="${s.id}"><div class="grow"><strong>${s.style?STYLES[s.style].n+' : ':''}${groupsLabel(s.groups)}</strong><small>${fmtDay(s.date)}, ${s.dur?fmtChrono(s.dur)+', ':''}${fmtN(r0(vol(s)))} kg soulevés</small></div>${ic('chev',18)}</button>`).join(''):''})()}
<div class="sh" style="margin-top:20px"><h2>Photos du mois</h2><span class="acc" id="phNote" style="font-size:13px"></span></div><div class="photos" id="photos"><p class="empty">Chargement…</p></div>
<div class="card sleepc" data-act="sleep" role="button" tabindex="0" style="margin-top:16px"><span class="sl">${ic('moon',24)}</span><div><strong>${avg?fmtH(avg)+' de sommeil en moyenne':'Aucune nuit notée'}</strong><small>${sleepInsight()}</small></div></div>`;
const sel=$('#exSel');if(sel)sel.addEventListener('change',()=>{progEx=sel.value;render()});
loadPhotos()}
ACT.kcaladj=el=>{const d=+el.dataset.d;const P=S.profile;P.kcal+=d;P.carb=Math.max(0,P.carb+Math.round(d/4));save();render();toast('Objectif : '+fmtN(P.kcal)+' kcal')};
ACT.weigh=()=>{sheet(`<h2>Nouvelle pesée</h2><form id="wF" class="form" novalidate><label>Poids (kg)<input name="kg" type="text" inputmode="decimal" placeholder="70,5"></label><button class="btn primary full" type="submit">Enregistrer</button></form>`);const f=$('#wF');f.addEventListener('submit',e=>{e.preventDefault();const kg=num(f.elements.kg.value);if(kg<30||kg>250){toast('Poids invalide');return}S.weights=S.weights.filter(w=>w.date!==dk());S.weights.push({date:dk(),kg});S.profile.kg=kg;save();closeSheet();render();toast('Pesée enregistrée')})};

// Photos (IndexedDB, sur le téléphone uniquement)
let photoCache=[];
function idb(){return new Promise((res,rej)=>{if(!window.indexedDB)return rej(new Error('no idb'));const r=indexedDB.open('coach-salle-photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('p',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function photoAll(){try{const db=await idb();return await new Promise((res,rej)=>{const q=db.transaction('p').objectStore('p').getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}catch(e){return null}}
async function photoTx(fn){const db=await idb();return new Promise((res,rej)=>{const tx=db.transaction('p','readwrite');fn(tx.objectStore('p'));tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function loadPhotos(){const box=$('#photos');if(!box)return;const all=await photoAll();const b=$('#photos');if(!b)return;if(all===null){b.innerHTML='<p class="empty">Les photos ne peuvent pas être stockées sur cet appareil.</p>';return}
all.sort((a,c)=>a.date<c.date?-1:1);photoCache=all;
b.innerHTML=all.map(p=>`<button class="ph" data-act="photo" data-id="${p.id}"><img src="${p.data}" alt="Photo du ${fmtDay(p.date)}"><span>${MOIS[parseDk(p.date).getMonth()]}</span></button>`).join('')+`<button class="ph add" data-act="addphoto" aria-label="Ajouter la photo du mois">${ic('camera',22)}</button>`;
const m=dk().slice(0,7),n=$('#phNote');if(n)n.textContent=all.some(p=>p.date.slice(0,7)===m)?'':'celle de '+MOISL[new Date().getMonth()]+' t’attend'}
ACT.addphoto=()=>$('#photoInput').click();
$('#photoInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const data=await shrink(f,1280);if(!data){toast('Photo illisible');return}try{await photoTx(st=>st.put({id:uid(),date:dk(),data}));toast('Photo ajoutée');loadPhotos()}catch(err){toast('Impossible d’enregistrer la photo')}});
ACT.photo=el=>{const p=photoCache.find(x=>x.id===el.dataset.id);if(!p)return;const firstP=photoCache[0];sheet(`<h2>${fmtDayLong(p.date)}</h2><img class="prev tall" src="${p.data}" alt="">${firstP&&firstP.id!==p.id?`<p class="lab">Ta première photo, ${fmtDay(firstP.date)}</p><img class="prev tall" src="${firstP.data}" alt="">`:''}<button class="btn ghost full" data-act="delphoto" data-id="${p.id}">Supprimer cette photo</button>`)};
ACT.delphoto=async el=>{try{await photoTx(st=>st.delete(el.dataset.id));closeSheet();loadPhotos();toast('Photo supprimée')}catch(e){toast('Suppression impossible')}};

// Réglages et sauvegarde
ACT.settings=()=>{const P=S.profile;sheet(`<h2>Réglages</h2><form id="stF" class="form" novalidate><p class="lab" style="margin-top:0">Objectifs par jour</p><div class="grid2"><label>Calories<input name="kcal" type="text" inputmode="numeric" value="${P.kcal}"></label><label>Protéines (g)<input name="prot" type="text" inputmode="numeric" value="${P.prot}"></label><label>Glucides (g)<input name="carb" type="text" inputmode="numeric" value="${P.carb}"></label><label>Lipides (g)<input name="fat" type="text" inputmode="numeric" value="${P.fat}"></label></div>
<p class="lab">Entraînement</p><label>Séances par semaine visées<input name="weekGoal" type="text" inputmode="numeric" value="${P.weekGoal||4}"></label>
<div class="grid2"><label>Repos entre les séries (s)<input name="rest" type="text" inputmode="numeric" value="${+P.rest||0}"></label><label>Repos, séries lourdes (s)<input name="restHeavy" type="text" inputmode="numeric" value="${+P.restHeavy||0}"></label></div><p class="note" style="margin-top:-4px">Séries lourdes : objectif de 8 répétitions ou moins. Mets 0 pour couper le minuteur.</p>
<p class="lab">Ton shaker de whey (dose de 31 g)</p><div class="grid2"><label>Calories<input name="wkcal" type="text" inputmode="decimal" value="${P.wkcal}"></label><label>Protéines (g)<input name="wprot" type="text" inputmode="decimal" value="${P.wprot}"></label><label>Glucides (g)<input name="wcarb" type="text" inputmode="decimal" value="${P.wcarb}"></label><label>Lipides (g)<input name="wfat" type="text" inputmode="decimal" value="${P.wfat}"></label></div>
<p class="lab">Profil</p><div class="grid2"><label>Taille (cm)<input name="cm" type="text" inputmode="numeric" value="${P.cm}"></label><label>Âge<input name="age" type="text" inputmode="numeric" value="${P.age}"></label></div><button class="btn primary full" type="submit">Enregistrer</button></form>
<p class="lab" style="margin-top:22px">Mes exercices</p>${EX.filter(x=>x.u).map(x=>`<button class="row" data-act="exinfo" data-ex="${x.id}"><span class="pict sm">${exPic(x,24)}</span><span class="grow"><strong>${x.n}</strong><small>${GN[x.g]}, ${x.m}</small></span>${ic('chev',18)}</button>`).join('')||'<p class="note">Un exercice manque dans la liste ? Crée-le ici, il sera proposé partout.</p>'}<button class="btn ghost full" data-act="newex">${ic('plus')} Créer un exercice</button>
<p class="lab" style="margin-top:22px">Lecture des étiquettes (clé API Anthropic)</p><form id="keyF" class="form" novalidate><label>Clé API${getApiKey()?' : enregistrée sur ce téléphone':''}<input name="key" type="password" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="${getApiKey()?'••••••••'+esc(getApiKey().slice(-4)):'sk-ant-...'}"></label><div class="grid2"><button class="btn primary" type="submit">Enregistrer et tester</button><button class="btn ghost" type="button" id="keyDel">Supprimer</button></div><p class="note" id="keyMsg">${sampleFn&&sampleFn.mode==='api'?'Mode actif : ta clé API.':sampleFn?'Mode actif : ton compte Claude.':'Aucune lecture automatique active.'} La clé reste sur ce téléphone et n’est jamais mise dans les sauvegardes.</p></form>
<p class="lab" style="margin-top:22px">Sauvegarde</p><p class="note">Tes données restent sur ce téléphone. Exporte une sauvegarde de temps en temps : elle contient tout, photos du mois comprises.</p>
<button class="btn ghost full" data-act="export">Exporter une sauvegarde</button><button class="btn ghost full" data-act="import">Restaurer une sauvegarde</button>`);
const kf=$('#keyF');kf.addEventListener('submit',async ev=>{ev.preventDefault();const k=kf.elements.key.value.trim();const msg=$('#keyMsg');if(!k){msg.textContent='Colle ta clé avant d’enregistrer.';return}if(!/^sk-ant-/.test(k)){msg.textContent='Une clé Anthropic commence par sk-ant-. Vérifie le copier-coller.';return}msg.textContent='Test en cours…';try{const r=await apiSample(k).json('Réponds avec {"ok":true}');if(!r||r.ok!==true)throw apiErr('api_error');setApiKey(k);kf.elements.key.value='';msg.textContent='Clé valide et enregistrée. La lecture des photos est activée.';await initAI()}catch(err){msg.textContent=errMsg(err&&err.code)+(err&&err.code==='api_error'&&err.message?' ('+err.message+')':'')}});
$('#keyDel').onclick=async()=>{setApiKey('');$('#keyMsg').textContent='Clé supprimée de ce téléphone.';await initAI()};
const f=$('#stF'),F=f.elements;f.addEventListener('submit',e=>{e.preventDefault();for(const k of['kcal','prot','carb','fat','cm','age','weekGoal']){const v=r0(num(F[k].value));if(v>0)P[k]=v}for(const k of['rest','restHeavy']){const v=r0(num(F[k].value));if(v>=0&&v<=900)P[k]=v}for(const k of['wkcal','wprot','wcarb','wfat']){const v=num(F[k].value);if(v>=0)P[k]=v}save();closeSheet();render();toast('Réglages enregistrés')})};
// Sauvegarde : toutes les données + les photos du mois. Sur iPhone on passe par la feuille de partage (« Enregistrer dans Fichiers »),
// plus fiable qu'un téléchargement quand l'app est installée sur l'écran d'accueil.
const IOS=/iP(hone|ad|od)/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
let bkFile=null;
function dlBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove()}
function exported(){S.lastExport=Date.now();save();closeSheet();render();toast('Sauvegarde exportée')}
ACT.export=async()=>{const fn=`coach-salle-${dk()}.json`;const photos=(await photoAll())||[];const data=JSON.stringify(Object.assign({},S,{photos}));
if(dlFn){try{await dlFn.save({filename:fn,data});exported()}catch(e){if(!e||e.code!=='declined')toast('Export impossible ici')}return}
if(framed){toast('Export indisponible dans cette vue');return}
const blob=new Blob([data],{type:'application/json'});let file=null;try{file=new File([blob],fn,{type:'application/json'})}catch(e){}
if(IOS&&file&&navigator.canShare&&navigator.canShare({files:[file]})){bkFile=file;sheet(`<h2>Sauvegarde prête</h2><p>Toutes tes données${photos.length?` et tes ${photos.length} photo${photos.length>1?'s':''}`:''} sont dans le fichier.</p><p class="note">Touche le bouton, puis choisis « Enregistrer dans Fichiers ».</p><button class="btn primary full" data-act="bkshare">Enregistrer le fichier</button>`);return}
dlBlob(blob,fn);exported()};
ACT.bkshare=async()=>{if(!bkFile)return;try{await navigator.share({files:[bkFile]});exported()}catch(e){if(e&&e.name==='AbortError')return;dlBlob(bkFile,bkFile.name);exported()}};
ACT.import=()=>$('#importInput').click();
const okPhoto=p=>p&&/^[\w-]+$/.test(p.id||'')&&/^\d{4}-\d{2}-\d{2}$/.test(p.date||'')&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+\/=]+$/.test(p.data||'');
$('#importInput').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;let d;try{d=JSON.parse(await f.text());if(!d||!Array.isArray(d.sessions)||!Array.isArray(d.meals))throw new Error('bad')}catch(err){toast('Ce fichier n’est pas une sauvegarde valide');return}
const ph=(Array.isArray(d.photos)?d.photos:[]).filter(okPhoto);delete d.photos;S=hydrate(d);syncEx();VD=null;save();let n=0;if(ph.length){try{await photoTx(st=>ph.forEach(p=>st.put({id:p.id,date:p.date,data:p.data})));n=ph.length}catch(err){}}
closeSheet();render();toast('Sauvegarde restaurée'+(n?` avec ${n} photo${n>1?'s':''}`:''))});

// ===== Navigation =====
let tab='today';try{tab=localStorage.getItem('coach-salle-tab')||'today'}catch(e){}
if(!['today','plan','gym','prog'].includes(tab))tab='today';
const TABS={today:['home','Aujourd’hui'],plan:['week','Planifier'],gym:['dumbbell','Salle'],prog:['chart','Progrès']};
document.querySelectorAll('.tabs button').forEach(b=>{const[i,l]=TABS[b.dataset.tab];b.innerHTML=ic(i,22)+'<span>'+l+'</span>'});
function setTab(t){if(t!=='plan'){PD=null;PDdone=null}tab=t;try{localStorage.setItem('coach-salle-tab',t)}catch(e){}closeSheet();render();window.scrollTo(0,0)}
function render(){autoClose();for(const t of['today','plan','gym','prog'])$('#v-'+t).hidden=t!==tab;document.querySelectorAll('.tabs button').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});({today:renderToday,plan:renderPlanTab,gym:renderGym,prog:renderProg})[tab]();drawRest()}
document.addEventListener('click',e=>{const tb=e.target.closest('[data-tab]');if(tb){setTab(tb.dataset.tab);return}if(e.target.id==='sheet'){closeSheet();return}const el=e.target.closest('[data-act]');if(!el)return;const fn=ACT[el.dataset.act];if(fn){e.preventDefault();fn(el)}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#sheet').hidden)closeSheet();if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role="button"][data-act]')){e.preventDefault();e.target.click()}});
setInterval(()=>{const c=$('#chrono'),a=activeSession();if(c&&a&&tab==='gym')c.textContent=fmtChrono(Date.now()-a.start);drawRest()},1000);
render();
// Mode hors ligne et installation sur l'écran d'accueil (uniquement hébergée par toi, en https ou en local)
// Quand une nouvelle version a été téléchargée en arrière-plan, on recharge la page tout seul (jamais pendant une saisie).
let needReload=false;
function tryReload(){if(!needReload||!$('#sheet').hidden||PD)return;needReload=false;try{const t=+sessionStorage.getItem('cs-reload')||0;if(Date.now()-t<30000)return;sessionStorage.setItem('cs-reload',String(Date.now()));sessionStorage.setItem('cs-updated','1')}catch(e){return}location.reload()}
if('serviceWorker' in navigator&&!framed&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1')){const sw=navigator.serviceWorker,had=!!sw.controller;let rt,lastChk=Date.now();
const ask=()=>{needReload=true;clearTimeout(rt);rt=setTimeout(tryReload,1500)};
sw.addEventListener('message',e=>{if(e.data&&e.data.type==='updated')ask()});
sw.addEventListener('controllerchange',()=>{if(had)ask()});
window.addEventListener('load',()=>sw.register('sw.js').catch(()=>{}));
// L'iPhone garde souvent l'app ouverte en arrière-plan : au retour, on redemande s'il y a du nouveau
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&sw.controller&&Date.now()-lastChk>5*6e4){lastChk=Date.now();sw.controller.postMessage('check')}});
setInterval(tryReload,3000)}
try{if(sessionStorage.getItem('cs-updated')){sessionStorage.removeItem('cs-updated');setTimeout(()=>toast('App mise à jour'),400)}}catch(e){}
